logging:
  level:
    org.springframework.boot.web.embedded.netty: DEBUG
    reactor.ipc.netty.http: DEBUG
    org.springframework.http.server.reactive.ReactorHttpHandlerAdapter: DEBUG
    org.mongodb.driver: DEBUG